/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mahmoud_INTERFACE1 (void);
GtkWidget* create_mahmoud_INTERFACE2_MG (void);
GtkWidget* create_Maissa_1 (void);
GtkWidget* create_maissa_2 (void);
GtkWidget* create_Maissa_3 (void);
GtkWidget* create_Maissa_4 (void);
GtkWidget* create_Louay2 (void);
GtkWidget* create_Jamel_1 (void);
GtkWidget* create_jamel_2 (void);
GtkWidget* create_WindowAzizUserLogin (void);
GtkWidget* create_windowFixedUserConnected_AG (void);
GtkWidget* create_windowGestionnaireUtilisateurs_AG (void);
GtkWidget* create_windowAddUser (void);
GtkWidget* create_windowUserAddedSucc_AG (void);
GtkWidget* create_windowUserEdit_AG (void);
GtkWidget* create_windowAreUSure_AG (void);
GtkWidget* create_yahAzizLogin (void);
GtkWidget* create_yahAzizListeElections (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_yah_aziz_ajouter_moudifier (void);
GtkWidget* create_Louay1 (void);
GtkWidget* create_mahmoud_interface3_MG (void);
GtkWidget* create_jamel3_JE (void);
GtkWidget* create_Supp_JE (void);
